### ISSUE TITLE
Implement some kind of "work dispatcher" either in web or as Computer with Modem

### ISSUE THREAD

**Issue by fgoebel** [Blast0r/TurtlePrograms#13]
the idea is that there is a central computer or web-service which tracks the configured fields and has knowledge how often a field should be harvested. It then can dispatch turtles to the fields to harvest...

stretch goal: measure the outcome of each run and adjust the times?

**Comment by r-goebel** [comment]
Add following enhancements:
- [x] stateless turtles: turtles do not need to know about any Position or field, everything is send by Computer
- [x] Harvesting times of fields are stored not based on computer Runtime but based on real time, to allow restarts
- [x] queing turtles after work is done and no field is to harvest
